#!/usr/bin/env python3
"""Deploy Team Utility Projection Runtime V1.

ONE-FILE deployment package.

The JavaScript runtime is embedded in this Python file because some ChatGPT
clients reject direct .js attachment downloads. The workflow only needs this
Python file. During --apply it generates and stages:
  scripts/team_utility_projection_runtime.js

The release itself:
- adds one external script tag to index.html;
- never rewrites static PLAYER_DB;
- uses refreshed projections only for starter selection;
- keeps Fundamental Value as Team Utility's accounting scale;
- excludes taxi/reserve-IR from starter eligibility;
- leaves TU_BENCH_WEIGHT at 0.15;
- adds the projection artifact to scheduled refresh;
- adds permanent repository regression coverage.
"""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
INDEX = ROOT / "index.html"
SCHEDULED = ROOT / ".github" / "workflows" / "scheduled-data-refresh.yml"
REGRESSION = ROOT / "scripts" / "validation" / "repo_regression_checks.py"
RUNTIME = ROOT / "scripts" / "team_utility_projection_runtime.js"

MARKER = "TEAM_UTILITY_PROJECTION_RUNTIME_V1"
SCRIPT_TAG = '<script src="scripts/team_utility_projection_runtime.js"></script>'

RUNTIME_TEXT = "/* Team Utility Projection Runtime V1\n *\n * Projection points choose WHO starts.\n * Fundamental Value remains the ONLY accounting unit for lineupDelta,\n * benchDelta, and final Team Utility.\n *\n * This file is generated by the Python deployment patcher. It intentionally\n * lives outside index.html so the giant static PLAYER_DB is never rewritten.\n */\n(function (global) {\n  'use strict';\n\n  const MARKER = 'TEAM_UTILITY_PROJECTION_RUNTIME_V1';\n  const PROJECTION_URL = 'scripts/artifacts/generated/team_utility_lineup_projections.json';\n  const MY_ROSTER_URL = 'data/my_roster.json';\n  const LEAGUE_ROSTERS_URL = 'data/league_rosters.json';\n\n  const DEDICATED = [\n    { pos: 'QB', count: 1 },\n    { pos: 'RB', count: 2 },\n    { pos: 'WR', count: 2 },\n    { pos: 'TE', count: 1 },\n    { pos: 'K', count: 1 },\n    { pos: 'DL', count: 2 },\n    { pos: 'LB', count: 2 },\n    { pos: 'DB', count: 2 },\n  ];\n\n  const FLEXES = [\n    { eligible: ['RB', 'WR', 'TE'], count: 1 },\n    { eligible: ['QB', 'RB', 'WR', 'TE'], count: 1 },\n    { eligible: ['DL', 'LB', 'DB'], count: 2 },\n  ];\n\n  function normalizeFallback(name) {\n    return String(name || '')\n      .toLowerCase()\n      .replace(/[.'’\\-]/g, '')\n      .replace(/\\s+/g, ' ')\n      .trim();\n  }\n\n  function canonicalKey(name) {\n    let key = typeof normalizeName === 'function'\n      ? normalizeName(name)\n      : normalizeFallback(name);\n\n    if (typeof resolveExistingKey === 'function') {\n      key = resolveExistingKey(key);\n    }\n    return key;\n  }\n\n  const fallbackPersonalSlots = Object.create(null);\n  for (const name of ['devin neal', 'drew allar', 'michael trigg', 'bryce lance', 'derrick moore']) {\n    fallbackPersonalSlots[canonicalKey(name)] = 'taxi';\n  }\n\n  const state = {\n    marker: MARKER,\n    projectionStatus: 'idle',\n    projectionsBySleeperId: null,\n    sleeperIdByKey: Object.create(null),\n    personalSlotByKey: fallbackPersonalSlots,\n    teamSlotByRosterId: Object.create(null),\n  };\n\n  global.TD_TEAM_UTILITY_RUNTIME = state;\n\n  function capturePlayer(raw, slot, slotMap) {\n    if (!raw) return;\n    const key = canonicalKey(raw.name);\n    if (!key) return;\n\n    slotMap[key] = slot;\n\n    if (raw.player_id !== undefined && raw.player_id !== null) {\n      state.sleeperIdByKey[key] = String(raw.player_id);\n    }\n  }\n\n  function capturePersonalRoster(data) {\n    const slotMap = Object.create(null);\n\n    for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {\n      for (const raw of (data && data[slot]) || []) {\n        capturePlayer(raw, slot, slotMap);\n      }\n    }\n\n    // Keep known fallback taxi metadata if a future source snapshot omits it.\n    for (const [key, slot] of Object.entries(fallbackPersonalSlots)) {\n      if (!slotMap[key]) slotMap[key] = slot;\n    }\n\n    state.personalSlotByKey = slotMap;\n  }\n\n  function captureLeagueRosters(data) {\n    const all = Object.create(null);\n\n    for (const roster of (data && data.rosters) || []) {\n      const slotMap = Object.create(null);\n\n      for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {\n        for (const raw of roster[slot] || []) {\n          capturePlayer(raw, slot, slotMap);\n        }\n      }\n\n      if (roster.roster_id !== undefined && roster.roster_id !== null) {\n        all[String(roster.roster_id)] = slotMap;\n      }\n    }\n\n    state.teamSlotByRosterId = all;\n  }\n\n  function currentSlotMap() {\n    try {\n      if (\n        typeof MY_ROSTER_ID !== 'undefined' &&\n        MY_ROSTER_ID !== null &&\n        state.teamSlotByRosterId[String(MY_ROSTER_ID)]\n      ) {\n        return state.teamSlotByRosterId[String(MY_ROSTER_ID)];\n      }\n    } catch (_) {\n      // Fall through to the personal roster map.\n    }\n\n    return state.personalSlotByKey;\n  }\n\n  function projectionByKey(key, pos) {\n    if (pos === 'K') return null;\n    if (state.projectionStatus !== 'ready' || !state.projectionsBySleeperId) {\n      return null;\n    }\n\n    const sleeperId = state.sleeperIdByKey[key];\n    if (!sleeperId) return null;\n\n    const row = state.projectionsBySleeperId[String(sleeperId)];\n    if (!row) return null;\n\n    const projection = Number(row.projection);\n    return Number.isFinite(projection) ? projection : null;\n  }\n\n  function lineupCompare(a, b) {\n    // The canonical projection artifact intentionally omits kickers.\n    if (a.pos === 'K' && b.pos === 'K') {\n      return b.value - a.value;\n    }\n\n    const aHasProjection = Number.isFinite(a.lineupProjection);\n    const bHasProjection = Number.isFinite(b.lineupProjection);\n\n    if (aHasProjection && bHasProjection) {\n      const diff = b.lineupProjection - a.lineupProjection;\n      return diff !== 0 ? diff : (b.value - a.value);\n    }\n\n    // Missing projection is unknown, never interpreted as zero.\n    if (aHasProjection !== bHasProjection) {\n      return aHasProjection ? -1 : 1;\n    }\n\n    // Safe fallback reproduces the prior FV starter ordering.\n    return b.value - a.value;\n  }\n\n  function buildPlayers(keys, slotByKey) {\n    const out = [];\n\n    for (const key of keys || []) {\n      if (typeof PLAYER_DB === 'undefined') continue;\n      const info = PLAYER_DB[key];\n      if (!info) continue;\n\n      const value = typeof playerValueByKey === 'function'\n        ? playerValueByKey(key)\n        : null;\n\n      if (!Number.isFinite(value) || value <= 0) continue;\n\n      const slot = (slotByKey && slotByKey[key]) || 'bench';\n\n      out.push({\n        key,\n        pos: info.pos,\n        value,\n        lineupProjection: projectionByKey(key, info.pos),\n        starterEligible: slot !== 'taxi' && slot !== 'reserve_ir',\n        rosterSlot: slot,\n      });\n    }\n\n    return out;\n  }\n\n  function optimizeLineup(players) {\n    const remaining = (players || []).slice().sort(lineupCompare);\n    const starters = [];\n\n    for (const slot of DEDICATED) {\n      for (let n = 0; n < slot.count; n += 1) {\n        const index = remaining.findIndex(\n          p => p.starterEligible !== false && p.pos === slot.pos\n        );\n        if (index < 0) break;\n        starters.push(remaining[index]);\n        remaining.splice(index, 1);\n      }\n    }\n\n    for (const flex of FLEXES) {\n      for (let n = 0; n < flex.count; n += 1) {\n        const index = remaining.findIndex(\n          p => p.starterEligible !== false && flex.eligible.includes(p.pos)\n        );\n        if (index < 0) break;\n        starters.push(remaining[index]);\n        remaining.splice(index, 1);\n      }\n    }\n\n    return { starters, bench: remaining };\n  }\n\n  function sumValue(players) {\n    return (players || []).reduce((sum, player) => sum + player.value, 0);\n  }\n\n  function buildPostSlotMap(preRosterKeys, postRosterKeys, preSlotByKey) {\n    const preSet = new Set(preRosterKeys || []);\n    const out = Object.create(null);\n\n    for (const key of postRosterKeys || []) {\n      // Existing assets retain their current roster state.\n      // Incoming trade assets default to active bench and are startable.\n      out[key] = (\n        preSet.has(key) &&\n        preSlotByKey &&\n        preSlotByKey[key]\n      ) ? preSlotByKey[key] : 'bench';\n    }\n\n    return out;\n  }\n\n  function calculateTeamUtilityV1(\n    preRosterKeys,\n    postRosterKeys,\n    preSlotByKey = currentSlotMap(),\n    postSlotByKey = null\n  ) {\n    const resolvedPreSlots = preSlotByKey || Object.create(null);\n    const resolvedPostSlots = postSlotByKey || buildPostSlotMap(\n      preRosterKeys,\n      postRosterKeys,\n      resolvedPreSlots\n    );\n\n    const pre = optimizeLineup(buildPlayers(preRosterKeys, resolvedPreSlots));\n    const post = optimizeLineup(buildPlayers(postRosterKeys, resolvedPostSlots));\n\n    const lineupDelta = sumValue(post.starters) - sumValue(pre.starters);\n    const benchDelta = sumValue(post.bench) - sumValue(pre.bench);\n\n    // The existing production constant remains authoritative. 0.15 is only\n    // the defensive fallback if the constant is unavailable.\n    const benchWeight = (\n      typeof TU_BENCH_WEIGHT !== 'undefined' &&\n      Number.isFinite(Number(TU_BENCH_WEIGHT))\n    ) ? Number(TU_BENCH_WEIGHT) : 0.15;\n\n    return {\n      teamUtility: Math.round(\n        (1 - benchWeight) * lineupDelta + benchWeight * benchDelta\n      ),\n      lineupDelta: Math.round(lineupDelta),\n      benchDelta: Math.round(benchDelta),\n    };\n  }\n\n  async function fetchJson(url) {\n    const response = await fetch(url, { cache: 'no-store' });\n    if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);\n    return response.json();\n  }\n\n  async function loadRuntimeData() {\n    if (typeof fetch !== 'function') {\n      state.projectionStatus = 'failed';\n      return;\n    }\n\n    state.projectionStatus = 'loading';\n\n    const [projectionResult, personalResult, leagueResult] = await Promise.allSettled([\n      fetchJson(PROJECTION_URL),\n      fetchJson(MY_ROSTER_URL),\n      fetchJson(LEAGUE_ROSTERS_URL),\n    ]);\n\n    if (personalResult.status === 'fulfilled') {\n      capturePersonalRoster(personalResult.value);\n    } else {\n      console.warn('Team Utility personal roster metadata unavailable:', personalResult.reason);\n    }\n\n    if (leagueResult.status === 'fulfilled') {\n      captureLeagueRosters(leagueResult.value);\n    } else {\n      console.warn('Team Utility league roster metadata unavailable:', leagueResult.reason);\n    }\n\n    if (projectionResult.status === 'fulfilled') {\n      const data = projectionResult.value;\n      const players = data && data.players;\n      const playerCount = players && typeof players === 'object'\n        ? Object.keys(players).length\n        : 0;\n\n      if (\n        data.schema_version === 1 &&\n        Number(data.season) === 2026 &&\n        playerCount >= 400\n      ) {\n        state.projectionsBySleeperId = players;\n        state.projectionStatus = 'ready';\n      } else {\n        state.projectionsBySleeperId = null;\n        state.projectionStatus = 'failed';\n        console.warn('Unexpected Team Utility projection artifact schema/coverage');\n      }\n    } else {\n      state.projectionsBySleeperId = null;\n      state.projectionStatus = 'failed';\n      console.warn(\n        'Team Utility projection artifact unavailable; using Fundamental Value starter ordering:',\n        projectionResult.reason\n      );\n    }\n\n    if (typeof render === 'function') render();\n  }\n\n  function installBrowserRuntime() {\n    // Existing UI calls the global function by name. Override only that public\n    // entry point; all static player/value code stays untouched.\n    global.calculateTeamUtility = calculateTeamUtilityV1;\n    loadRuntimeData();\n  }\n\n  function selftest() {\n    function p(key, pos, value, projection, slot = 'bench') {\n      return {\n        key,\n        pos,\n        value,\n        lineupProjection: projection,\n        starterEligible: slot !== 'taxi' && slot !== 'reserve_ir',\n        rosterSlot: slot,\n      };\n    }\n\n    const qb = optimizeLineup([\n      p('high_fv_low_proj', 'QB', 9000, 100),\n      p('low_fv_high_proj', 'QB', 3000, 300),\n    ]);\n    if (!qb.starters.some(player => player.key === 'low_fv_high_proj')) {\n      throw new Error('projection objective failed');\n    }\n\n    const taxi = optimizeLineup([\n      p('active_qb', 'QB', 1000, 100),\n      p('taxi_qb', 'QB', 20000, 900, 'taxi'),\n    ]);\n    if (taxi.starters.some(player => player.key === 'taxi_qb')) {\n      throw new Error('taxi starter guard failed');\n    }\n    if (!taxi.bench.some(player => player.key === 'taxi_qb')) {\n      throw new Error('taxi disappeared from bench economics');\n    }\n\n    const ordered = [\n      p('missing', 'WR', 10000, null),\n      p('known_zero', 'WR', 1000, 0),\n    ].sort(lineupCompare);\n    if (ordered[0].key !== 'known_zero') {\n      throw new Error('missing projection treated as zero');\n    }\n\n    const slots = buildPostSlotMap(\n      ['taxi_keep', 'wr_keep'],\n      ['taxi_keep', 'wr_keep', 'incoming'],\n      { taxi_keep: 'taxi', wr_keep: 'bench' }\n    );\n    if (slots.taxi_keep !== 'taxi') {\n      throw new Error('existing taxi state not preserved');\n    }\n    if (slots.incoming !== 'bench') {\n      throw new Error('incoming asset not made starter-eligible');\n    }\n\n    const full = [];\n    let id = 0;\n    for (const [pos, count] of [\n      ['QB', 2], ['RB', 3], ['WR', 3], ['TE', 2], ['K', 1],\n      ['DL', 4], ['LB', 4], ['DB', 4],\n    ]) {\n      for (let i = 0; i < count; i += 1) {\n        id += 1;\n        full.push(p(`${pos}${id}`, pos, 1000 - id, 500 - id));\n      }\n    }\n\n    const optimized = optimizeLineup(full);\n    if (optimized.starters.length !== 17) {\n      throw new Error(`expected 17 legal starters, got ${optimized.starters.length}`);\n    }\n\n    console.log('PASS Team Utility projection runtime self-test');\n  }\n\n  global.TD_TEAM_UTILITY_RUNTIME_API = {\n    lineupCompare,\n    optimizeLineup,\n    buildPostSlotMap,\n    calculateTeamUtilityV1,\n    selftest,\n  };\n\n  if (\n    typeof process !== 'undefined' &&\n    process.argv &&\n    process.argv.includes('--selftest')\n  ) {\n    selftest();\n  } else if (typeof window !== 'undefined' && global === window) {\n    installBrowserRuntime();\n  }\n})(typeof window !== 'undefined' ? window : globalThis);\n"

REGRESSION_FN = '\ndef check_team_utility_projection_runtime_invariants():\n    runtime = REPO_ROOT / "scripts" / "team_utility_projection_runtime.js"\n    builder = REPO_ROOT / "scripts" / "projections" / "build_team_utility_lineup_projections.py"\n\n    assert runtime.exists(), "missing Team Utility projection runtime"\n    subprocess.run(["node", "--check", str(runtime)], cwd=REPO_ROOT, check=True)\n    subprocess.run(["node", str(runtime), "--selftest"], cwd=REPO_ROOT, check=True)\n    subprocess.run([sys.executable, str(builder), "--check"], cwd=REPO_ROOT, check=True)\n\n    text = INDEX.read_text(encoding="utf-8")\n    assert \'<script src="scripts/team_utility_projection_runtime.js"></script>\' in text\n    assert "const TU_BENCH_WEIGHT = 0.15;" in text, (\n        "bench-weight calibration changed in starter-objective release"\n    )\n    snapshot_values.extract_object_body(text, "PLAYER_DB")\n\n    runtime_text = runtime.read_text(encoding="utf-8")\n    for token in (\n        "TEAM_UTILITY_PROJECTION_RUNTIME_V1",\n        "projectionByKey",\n        "starterEligible: slot !== \'taxi\' && slot !== \'reserve_ir\'",\n        "buildPostSlotMap",\n        "calculateTeamUtilityV1",\n        "data/my_roster.json",\n        "data/league_rosters.json",\n    ):\n        assert token in runtime_text, f"runtime missing invariant token: {token}"\n\n    print(\n        "PASS Team Utility projection-runtime invariants: artifact current; "\n        "runtime syntax/selftest green; PLAYER_DB still parseable; "\n        "TU_BENCH_WEIGHT unchanged"\n    )\n'


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected exactly 1 match, found {count}")
    return text.replace(old, new, 1)


def load_snapshot_guard():
    path = ROOT / "scripts" / "validation" / "snapshot_values.py"
    spec = importlib.util.spec_from_file_location("tu_snapshot_guard", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load snapshot_values.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def validate_embedded_runtime():
    with tempfile.NamedTemporaryFile(
        "w", suffix=".js", delete=False, encoding="utf-8"
    ) as handle:
        handle.write(RUNTIME_TEXT)
        path = Path(handle.name)

    try:
        subprocess.run(["node", "--check", str(path)], check=True)
        proc = subprocess.run(
            ["node", str(path), "--selftest"],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        if "PASS Team Utility projection runtime self-test" not in proc.stdout:
            raise RuntimeError("embedded runtime self-test did not report PASS")
    finally:
        path.unlink(missing_ok=True)


def patch_index(text):
    if SCRIPT_TAG in text:
        return text

    return replace_once(
        text,
        "</body>",
        f"{SCRIPT_TAG}\n</body>",
        "external Team Utility runtime script tag",
    )


def patch_scheduled(text):
    if "Refresh Team Utility lineup projections" not in text:
        text = replace_once(
            text,
            """      - name: Refresh FantasyPros-Sleeper identity crosswalk
        run: python3 scripts/projections/resolve_fantasypros_sleeper_identity.py

      - name: Dual-eligibility self-test
""",
            """      - name: Refresh FantasyPros-Sleeper identity crosswalk
        run: python3 scripts/projections/resolve_fantasypros_sleeper_identity.py

      - name: Team Utility lineup projection self-test
        run: python3 scripts/projections/build_team_utility_lineup_projections.py --selftest

      - name: Refresh Team Utility lineup projections
        run: python3 scripts/projections/build_team_utility_lineup_projections.py --write

      - name: Verify Team Utility lineup projection artifact
        run: python3 scripts/projections/build_team_utility_lineup_projections.py --check

      - name: Dual-eligibility self-test
""",
            "scheduled Team Utility projection build",
        )

    if "git add scripts/artifacts/generated/team_utility_lineup_projections.json" not in text:
        text = replace_once(
            text,
            """          git add scripts/identity_crosswalk.json
          git add scripts/artifacts/reports/identity_collision_report.md
          git add scripts/artifacts/generated/dual_eligibility_results.json
""",
            """          git add scripts/identity_crosswalk.json
          git add scripts/artifacts/reports/identity_collision_report.md
          git add scripts/artifacts/generated/team_utility_lineup_projections.json
          git add scripts/artifacts/reports/team_utility_lineup_projection_report.md
          git add scripts/artifacts/generated/dual_eligibility_results.json
""",
            "scheduled Team Utility artifact staging",
        )

    return text


def patch_regression(text):
    if "check_team_utility_projection_runtime_invariants" not in text:
        text = replace_once(
            text,
            "def check_index_js_syntax():\n",
            REGRESSION_FN + "\n\ndef check_index_js_syntax():\n",
            "Team Utility runtime regression function insertion",
        )

        text = replace_once(
            text,
            """        check_free_agent_board_parity,
        check_index_js_syntax,
""",
            """        check_free_agent_board_parity,
        check_team_utility_projection_runtime_invariants,
        check_index_js_syntax,
""",
            "Team Utility runtime regression registration",
        )

    return text


def check_inline_js(index_text):
    scripts = re.findall(r"<script[^>]*>(.*?)</script>", index_text, re.S | re.I)

    with tempfile.NamedTemporaryFile(
        "w", suffix=".js", delete=False, encoding="utf-8"
    ) as handle:
        handle.write("\n".join(scripts))
        path = Path(handle.name)

    try:
        subprocess.run(
            ["node", "--check", str(path)],
            check=True,
            capture_output=True,
            text=True,
        )
    finally:
        path.unlink(missing_ok=True)


def build():
    validate_embedded_runtime()

    old_index = INDEX.read_text(encoding="utf-8")
    old_scheduled = SCHEDULED.read_text(encoding="utf-8")
    old_regression = REGRESSION.read_text(encoding="utf-8")

    new_index = patch_index(old_index)
    new_scheduled = patch_scheduled(old_scheduled)
    new_regression = patch_regression(old_regression)

    compile(new_regression, str(REGRESSION), "exec")
    check_inline_js(new_index)

    snapshot_guard = load_snapshot_guard()
    old_player_body = snapshot_guard.extract_object_body(old_index, "PLAYER_DB")
    new_player_body = snapshot_guard.extract_object_body(new_index, "PLAYER_DB")
    if old_player_body != new_player_body:
        raise RuntimeError(
            "Team Utility deployment unexpectedly changed static PLAYER_DB"
        )

    before = re.search(r"const TU_BENCH_WEIGHT = ([^;]+);", old_index)
    after = re.search(r"const TU_BENCH_WEIGHT = ([^;]+);", new_index)
    if not before or not after or before.group(1) != after.group(1):
        raise RuntimeError("TU_BENCH_WEIGHT changed unexpectedly")

    if new_index.count(SCRIPT_TAG) != 1:
        raise RuntimeError("Team Utility runtime script tag count is not exactly 1")

    return new_index, new_scheduled, new_regression


def selftest():
    build()
    print("PASS Team Utility one-file deployment dry run")
    print("PASS embedded runtime Node syntax + synthetic self-test")
    print("PASS generated regression Python syntax")
    print("PASS index.html inline JavaScript syntax")
    print("PASS static PLAYER_DB parser/body unchanged")
    print("PASS TU_BENCH_WEIGHT unchanged")


def apply():
    new_index, new_scheduled, new_regression = build()

    RUNTIME.parent.mkdir(parents=True, exist_ok=True)
    RUNTIME.write_text(RUNTIME_TEXT, encoding="utf-8")
    INDEX.write_text(new_index, encoding="utf-8")
    SCHEDULED.write_text(new_scheduled, encoding="utf-8")
    REGRESSION.write_text(new_regression, encoding="utf-8")

    # The existing deployment workflow's git-add list predates the external
    # runtime. Stage the generated JS here so NO workflow replacement is needed.
    if (ROOT / ".git").exists():
        subprocess.run(
            ["git", "add", "scripts/team_utility_projection_runtime.js"],
            cwd=ROOT,
            check=True,
        )

    print("Applied TEAM_UTILITY_PROJECTION_RUNTIME_V1")
    print("Generated and staged:")
    print("  scripts/team_utility_projection_runtime.js")
    print("Changed:")
    print("  index.html (one external script tag only)")
    print("  .github/workflows/scheduled-data-refresh.yml")
    print("  scripts/validation/repo_regression_checks.py")
    print("Protected unchanged:")
    print("  static PLAYER_DB")
    print("  TU_BENCH_WEIGHT")


def main():
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--selftest", action="store_true")
    mode.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        selftest()
    else:
        apply()


if __name__ == "__main__":
    main()
