/* Team Utility Projection Runtime V1
 *
 * Projection points choose WHO starts.
 * Fundamental Value remains the ONLY accounting unit for lineupDelta,
 * benchDelta, and final Team Utility.
 *
 * This file is generated by the Python deployment patcher. It intentionally
 * lives outside index.html so the giant static PLAYER_DB is never rewritten.
 */
(function (global) {
  'use strict';

  const MARKER = 'TEAM_UTILITY_PROJECTION_RUNTIME_V1';
  const PROJECTION_URL = 'scripts/artifacts/generated/team_utility_lineup_projections.json';
  const MY_ROSTER_URL = 'data/my_roster.json';
  const LEAGUE_ROSTERS_URL = 'data/league_rosters.json';

  const DEDICATED = [
    { pos: 'QB', count: 1 },
    { pos: 'RB', count: 2 },
    { pos: 'WR', count: 2 },
    { pos: 'TE', count: 1 },
    { pos: 'K', count: 1 },
    { pos: 'DL', count: 2 },
    { pos: 'LB', count: 2 },
    { pos: 'DB', count: 2 },
  ];

  const FLEXES = [
    { eligible: ['RB', 'WR', 'TE'], count: 1 },
    { eligible: ['QB', 'RB', 'WR', 'TE'], count: 1 },
    { eligible: ['DL', 'LB', 'DB'], count: 2 },
  ];

  function normalizeFallback(name) {
    return String(name || '')
      .toLowerCase()
      .replace(/[.'’\-]/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function canonicalKey(name) {
    let key = typeof normalizeName === 'function'
      ? normalizeName(name)
      : normalizeFallback(name);

    if (typeof resolveExistingKey === 'function') {
      key = resolveExistingKey(key);
    }
    return key;
  }

  const fallbackPersonalSlots = Object.create(null);
  for (const name of ['devin neal', 'drew allar', 'michael trigg', 'bryce lance', 'derrick moore']) {
    fallbackPersonalSlots[canonicalKey(name)] = 'taxi';
  }

  const state = {
    marker: MARKER,
    projectionStatus: 'idle',
    projectionsBySleeperId: null,
    sleeperIdByKey: Object.create(null),
    personalSlotByKey: fallbackPersonalSlots,
    teamSlotByRosterId: Object.create(null),
  };

  global.TD_TEAM_UTILITY_RUNTIME = state;

  function capturePlayer(raw, slot, slotMap) {
    if (!raw) return;
    const key = canonicalKey(raw.name);
    if (!key) return;

    slotMap[key] = slot;

    if (raw.player_id !== undefined && raw.player_id !== null) {
      state.sleeperIdByKey[key] = String(raw.player_id);
    }
  }

  function capturePersonalRoster(data) {
    const slotMap = Object.create(null);

    for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {
      for (const raw of (data && data[slot]) || []) {
        capturePlayer(raw, slot, slotMap);
      }
    }

    for (const [key, slot] of Object.entries(fallbackPersonalSlots)) {
      if (!slotMap[key]) slotMap[key] = slot;
    }

    state.personalSlotByKey = slotMap;
  }

  function captureLeagueRosters(data) {
    const all = Object.create(null);

    for (const roster of (data && data.rosters) || []) {
      const slotMap = Object.create(null);

      for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {
        for (const raw of roster[slot] || []) {
          capturePlayer(raw, slot, slotMap);
        }
      }

      if (roster.roster_id !== undefined && roster.roster_id !== null) {
        all[String(roster.roster_id)] = slotMap;
      }
    }

    state.teamSlotByRosterId = all;
  }

  function currentSlotMap() {
    try {
      if (
        typeof MY_ROSTER_ID !== 'undefined' &&
        MY_ROSTER_ID !== null &&
        state.teamSlotByRosterId[String(MY_ROSTER_ID)]
      ) {
        return state.teamSlotByRosterId[String(MY_ROSTER_ID)];
      }
    } catch (_) {
      // Fall through to the personal roster map.
    }

    return state.personalSlotByKey;
  }

  function projectionByKey(key, pos) {
    if (pos === 'K') return null;
    if (state.projectionStatus !== 'ready' || !state.projectionsBySleeperId) {
      return null;
    }

    const sleeperId = state.sleeperIdByKey[key];
    if (!sleeperId) return null;

    const row = state.projectionsBySleeperId[String(sleeperId)];
    if (!row) return null;

    const projection = Number(row.projection);
    return Number.isFinite(projection) ? projection : null;
  }

  function lineupCompare(a, b) {
    if (a.pos === 'K' && b.pos === 'K') {
      return b.value - a.value;
    }

    const aHasProjection = Number.isFinite(a.lineupProjection);
    const bHasProjection = Number.isFinite(b.lineupProjection);

    if (aHasProjection && bHasProjection) {
      const diff = b.lineupProjection - a.lineupProjection;
      return diff !== 0 ? diff : (b.value - a.value);
    }

    if (aHasProjection !== bHasProjection) {
      return aHasProjection ? -1 : 1;
    }

    return b.value - a.value;
  }

  function buildPlayers(keys, slotByKey) {
    const out = [];

    for (const key of keys || []) {
      if (typeof PLAYER_DB === 'undefined') continue;
      const info = PLAYER_DB[key];
      if (!info) continue;

      const value = typeof playerValueByKey === 'function'
        ? playerValueByKey(key)
        : null;

      if (!Number.isFinite(value) || value <= 0) continue;

      const slot = (slotByKey && slotByKey[key]) || 'bench';

      out.push({
        key,
        pos: info.pos,
        value,
        lineupProjection: projectionByKey(key, info.pos),
        starterEligible: slot !== 'taxi' && slot !== 'reserve_ir',
        rosterSlot: slot,
      });
    }

    return out;
  }

  function optimizeLineup(players) {
    const remaining = (players || []).slice().sort(lineupCompare);
    const starters = [];

    for (const slot of DEDICATED) {
      for (let n = 0; n < slot.count; n += 1) {
        const index = remaining.findIndex(
          p => p.starterEligible !== false && p.pos === slot.pos
        );
        if (index < 0) break;
        starters.push(remaining[index]);
        remaining.splice(index, 1);
      }
    }

    for (const flex of FLEXES) {
      for (let n = 0; n < flex.count; n += 1) {
        const index = remaining.findIndex(
          p => p.starterEligible !== false && flex.eligible.includes(p.pos)
        );
        if (index < 0) break;
        starters.push(remaining[index]);
        remaining.splice(index, 1);
      }
    }

    return { starters, bench: remaining };
  }

  function sumValue(players) {
    return (players || []).reduce((sum, player) => sum + player.value, 0);
  }

  function buildPostSlotMap(preRosterKeys, postRosterKeys, preSlotByKey) {
    const preSet = new Set(preRosterKeys || []);
    const out = Object.create(null);

    for (const key of postRosterKeys || []) {
      out[key] = (
        preSet.has(key) &&
        preSlotByKey &&
        preSlotByKey[key]
      ) ? preSlotByKey[key] : 'bench';
    }

    return out;
  }

  function calculateTeamUtilityV1(
    preRosterKeys,
    postRosterKeys,
    preSlotByKey = currentSlotMap(),
    postSlotByKey = null
  ) {
    const resolvedPreSlots = preSlotByKey || Object.create(null);
    const resolvedPostSlots = postSlotByKey || buildPostSlotMap(
      preRosterKeys,
      postRosterKeys,
      resolvedPreSlots
    );

    const pre = optimizeLineup(buildPlayers(preRosterKeys, resolvedPreSlots));
    const post = optimizeLineup(buildPlayers(postRosterKeys, resolvedPostSlots));

    const lineupDelta = sumValue(post.starters) - sumValue(pre.starters);
    const benchDelta = sumValue(post.bench) - sumValue(pre.bench);

    const benchWeight = (
      typeof TU_BENCH_WEIGHT !== 'undefined' &&
      Number.isFinite(Number(TU_BENCH_WEIGHT))
    ) ? Number(TU_BENCH_WEIGHT) : 0.15;

    return {
      teamUtility: Math.round(
        (1 - benchWeight) * lineupDelta + benchWeight * benchDelta
      ),
      lineupDelta: Math.round(lineupDelta),
      benchDelta: Math.round(benchDelta),
    };
  }

  async function fetchJson(url) {
    const response = await fetch(url, { cache: 'no-store' });
    if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
    return response.json();
  }

  async function loadRuntimeData() {
    if (typeof fetch !== 'function') {
      state.projectionStatus = 'failed';
      return;
    }

    state.projectionStatus = 'loading';

    const [projectionResult, personalResult, leagueResult] = await Promise.allSettled([
      fetchJson(PROJECTION_URL),
      fetchJson(MY_ROSTER_URL),
      fetchJson(LEAGUE_ROSTERS_URL),
    ]);

    if (personalResult.status === 'fulfilled') {
      capturePersonalRoster(personalResult.value);
    } else {
      console.warn('Team Utility personal roster metadata unavailable:', personalResult.reason);
    }

    if (leagueResult.status === 'fulfilled') {
      captureLeagueRosters(leagueResult.value);
    } else {
      console.warn('Team Utility league roster metadata unavailable:', leagueResult.reason);
    }

    if (projectionResult.status === 'fulfilled') {
      const data = projectionResult.value;
      const players = data && data.players;
      const playerCount = players && typeof players === 'object'
        ? Object.keys(players).length
        : 0;

      if (
        data.schema_version === 1 &&
        Number(data.season) === 2026 &&
        playerCount >= 400
      ) {
        state.projectionsBySleeperId = players;
        state.projectionStatus = 'ready';
      } else {
        state.projectionsBySleeperId = null;
        state.projectionStatus = 'failed';
        console.warn('Unexpected Team Utility projection artifact schema/coverage');
      }
    } else {
      state.projectionsBySleeperId = null;
      state.projectionStatus = 'failed';
      console.warn(
        'Team Utility projection artifact unavailable; using Fundamental Value starter ordering:',
        projectionResult.reason
      );
    }

    if (typeof render === 'function') render();
  }

  function installBrowserRuntime() {
    global.calculateTeamUtility = calculateTeamUtilityV1;
    loadRuntimeData();
  }

  function selftest() {
    function p(key, pos, value, projection, slot = 'bench') {
      return {
        key,
        pos,
        value,
        lineupProjection: projection,
        starterEligible: slot !== 'taxi' && slot !== 'reserve_ir',
        rosterSlot: slot,
      };
    }

    const qb = optimizeLineup([
      p('high_fv_low_proj', 'QB', 9000, 100),
      p('low_fv_high_proj', 'QB', 3000, 300),
    ]);
    if (!qb.starters.some(player => player.key === 'low_fv_high_proj')) {
      throw new Error('projection objective failed');
    }

    const taxi = optimizeLineup([
      p('active_qb', 'QB', 1000, 100),
      p('taxi_qb', 'QB', 20000, 900, 'taxi'),
    ]);
    if (taxi.starters.some(player => player.key === 'taxi_qb')) {
      throw new Error('taxi starter guard failed');
    }
    if (!taxi.bench.some(player => player.key === 'taxi_qb')) {
      throw new Error('taxi disappeared from bench economics');
    }

    const ordered = [
      p('missing', 'WR', 10000, null),
      p('known_zero', 'WR', 1000, 0),
    ].sort(lineupCompare);
    if (ordered[0].key !== 'known_zero') {
      throw new Error('missing projection treated as zero');
    }

    const slots = buildPostSlotMap(
      ['taxi_keep', 'wr_keep'],
      ['taxi_keep', 'wr_keep', 'incoming'],
      { taxi_keep: 'taxi', wr_keep: 'bench' }
    );
    if (slots.taxi_keep !== 'taxi') {
      throw new Error('existing taxi state not preserved');
    }
    if (slots.incoming !== 'bench') {
      throw new Error('incoming asset not made starter-eligible');
    }

    const full = [];
    let id = 0;
    for (const [pos, count] of [
      ['QB', 2], ['RB', 3], ['WR', 3], ['TE', 2], ['K', 1],
      ['DL', 4], ['LB', 4], ['DB', 4],
    ]) {
      for (let i = 0; i < count; i += 1) {
        id += 1;
        full.push(p(`${pos}${id}`, pos, 1000 - id, 500 - id));
      }
    }

    const optimized = optimizeLineup(full);
    if (optimized.starters.length !== 17) {
      throw new Error(`expected 17 legal starters, got ${optimized.starters.length}`);
    }

    console.log('PASS Team Utility projection runtime self-test');
  }

  global.TD_TEAM_UTILITY_RUNTIME_API = {
    lineupCompare,
    optimizeLineup,
    buildPostSlotMap,
    calculateTeamUtilityV1,
    selftest,
  };

  if (
    typeof process !== 'undefined' &&
    process.argv &&
    process.argv.includes('--selftest')
  ) {
    selftest();
  } else if (typeof window !== 'undefined' && global === window) {
    installBrowserRuntime();
  }
})(typeof window !== 'undefined' ? window : globalThis);

/* Runtime-only player valuation integrity guard V1 — 2026-09-05
 *
 * A player first discovered through the live Sleeper roster merge must never
 * receive a Fundamental Value boost merely because a dynasty manager placed
 * him in a fantasy starter/bench slot. The inline legacy merge maps fantasy
 * starter/bench/taxi to Starter/Rotational/Speculative for previously unknown
 * players; this guard corrects that runtime-only path without changing any
 * baked PLAYER_DB, PROD_MULT, age curve, position weight, or frozen research
 * coefficient.
 *
 * Canonical/model-covered players remain on the existing valuation path.
 * Runtime-only players with no PROD_MULT fail conservatively at the canonical
 * 0.15 production floor until the normal model pipeline bakes real evidence.
 */
(function (global) {
  'use strict';

  const MARKER = 'RUNTIME_ONLY_PLAYER_VALUE_GUARD_V1';
  const MISSING_MODEL_FLOOR = 0.15;

  function fallbackKey(name) {
    return String(name || '')
      .toLowerCase()
      .replace(/[.'’\-]/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function keyFor(name) {
    let key = typeof normalizeName === 'function'
      ? normalizeName(name)
      : fallbackKey(name);
    if (typeof resolveExistingKey === 'function') key = resolveExistingKey(key);
    return key;
  }

  function hasCanonicalProduction(key) {
    return typeof PROD_MULT !== 'undefined' &&
      Object.prototype.hasOwnProperty.call(PROD_MULT, key);
  }

  function hasNoHistoryMarker(key) {
    return typeof NO_REAL_PRODUCTION_HISTORY !== 'undefined' &&
      Object.prototype.hasOwnProperty.call(NO_REAL_PRODUCTION_HISTORY, key);
  }

  function runtimeRoleFromDepth(pos, depthChartOrder) {
    const depth = Number(depthChartOrder);
    if (pos === 'QB') {
      if (depth === 1) return 'Starter';
      if (depth === 2) return 'Understudy';
      if (Number.isFinite(depth) && depth >= 3) return 'Speculative';
    }
    return 'Speculative';
  }

  function guardedProductionValue(isRuntimeOnly, hasProduction, originalValue) {
    return isRuntimeOnly && !hasProduction ? MISSING_MODEL_FLOOR : originalValue;
  }

  function applyRuntimeMetadata(raw, beforeKeys) {
    if (!raw || typeof PLAYER_DB === 'undefined') return;
    const key = keyFor(raw.name);
    if (!key) return;
    const info = PLAYER_DB[key];
    if (!info) return;

    const wasNew = beforeKeys && !beforeKeys.has(key);
    if (!wasNew && !info.runtimeSyncedOnly) return;

    info.runtimeSyncedOnly = true;
    info.depth_chart_order = raw.depth_chart_order ?? info.depth_chart_order ?? null;
    info.years_exp = raw.years_exp ?? info.years_exp ?? null;
    info.role = runtimeRoleFromDepth(info.pos, info.depth_chart_order);
  }

  function applyPersonalPayload(data, beforeKeys) {
    for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {
      for (const raw of (data && data[slot]) || []) {
        applyRuntimeMetadata(raw, beforeKeys);
      }
    }
  }

  function applyLeaguePayload(data, beforeKeys) {
    for (const roster of (data && data.rosters) || []) {
      for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {
        for (const raw of roster[slot] || []) {
          applyRuntimeMetadata(raw, beforeKeys);
        }
      }
    }
  }

  function recoverAlreadyMergedRuntimeQBs() {
    if (typeof PLAYER_DB === 'undefined') return;
    for (const [key, info] of Object.entries(PLAYER_DB)) {
      if (!info || info.pos !== 'QB' || info.currentlyRostered !== true) continue;
      if (hasCanonicalProduction(key) || hasNoHistoryMarker(key)) continue;
      if (info.pts2025 !== undefined || info.proj2026 !== undefined) continue;
      info.runtimeSyncedOnly = true;
      info.role = runtimeRoleFromDepth(info.pos, info.depth_chart_order);
    }
  }

  function installBrowserGuard() {
    if (
      typeof PLAYER_DB === 'undefined' ||
      typeof global.productionMultiplier !== 'function'
    ) {
      console.warn(`${MARKER}: valuation globals unavailable; guard not installed`);
      return;
    }

    const originalProductionMultiplier = global.productionMultiplier;
    global.productionMultiplier = function runtimeGuardedProductionMultiplier(name, role) {
      const key = keyFor(name);
      const info = PLAYER_DB[key];
      const originalValue = originalProductionMultiplier(name, role);
      return guardedProductionValue(
        !!(info && info.runtimeSyncedOnly),
        hasCanonicalProduction(key),
        originalValue
      );
    };

    if (typeof global.mergeLiveRoster === 'function') {
      const originalMergeLiveRoster = global.mergeLiveRoster;
      global.mergeLiveRoster = function runtimeGuardedMergeLiveRoster(data) {
        const beforeKeys = new Set(Object.keys(PLAYER_DB));
        const result = originalMergeLiveRoster(data);
        applyPersonalPayload(data, beforeKeys);
        return result;
      };
    }

    if (typeof global.mergeLeagueRosters === 'function') {
      const originalMergeLeagueRosters = global.mergeLeagueRosters;
      global.mergeLeagueRosters = function runtimeGuardedMergeLeagueRosters(data) {
        const beforeKeys = new Set(Object.keys(PLAYER_DB));
        const result = originalMergeLeagueRosters(data);
        applyLeaguePayload(data, beforeKeys);
        return result;
      };
    }

    recoverAlreadyMergedRuntimeQBs();
    global.TD_RUNTIME_PLAYER_VALUE_GUARD = {
      marker: MARKER,
      floor: MISSING_MODEL_FLOOR,
      runtimeRoleFromDepth,
    };
  }

  function selftest() {
    const roles = [
      runtimeRoleFromDepth('QB', 1),
      runtimeRoleFromDepth('QB', 2),
      runtimeRoleFromDepth('QB', 3),
      runtimeRoleFromDepth('QB', null),
      runtimeRoleFromDepth('WR', 1),
    ];
    const expectedRoles = ['Starter', 'Understudy', 'Speculative', 'Speculative', 'Speculative'];
    if (JSON.stringify(roles) !== JSON.stringify(expectedRoles)) {
      throw new Error(`runtime depth-role guard failed: ${JSON.stringify(roles)}`);
    }

    const slotInflationInputs = [1.0, 0.65, 0.57, 0.22];
    for (const originalValue of slotInflationInputs) {
      if (guardedProductionValue(true, false, originalValue) !== MISSING_MODEL_FLOOR) {
        throw new Error('runtime missing-model floor depends on fantasy/role estimate');
      }
    }
    if (guardedProductionValue(false, false, 0.65) !== 0.65) {
      throw new Error('curated missing-production fallback changed');
    }
    if (guardedProductionValue(true, true, 0.65) !== 0.65) {
      throw new Error('canonical production was overridden');
    }

    console.log('PASS Runtime-only player valuation guard self-test');
  }

  if (
    typeof process !== 'undefined' &&
    process.argv &&
    process.argv.includes('--selftest')
  ) {
    selftest();
  } else if (typeof window !== 'undefined' && global === window) {
    installBrowserGuard();
  }
})(typeof window !== 'undefined' ? window : globalThis);
