/* Team Utility Projection Runtime V1
 *
 * Projection points choose WHO starts.
 * Fundamental Value remains the ONLY accounting unit for lineupDelta,
 * benchDelta, and final Team Utility.
 *
 * This file is generated by the Python deployment patcher. It intentionally
 * lives outside index.html so the giant static PLAYER_DB is never rewritten.
 */
(function (global) {
  'use strict';

  const MARKER = 'TEAM_UTILITY_PROJECTION_RUNTIME_V1';
  const PROJECTION_URL = 'scripts/artifacts/generated/team_utility_lineup_projections.json';
  const MY_ROSTER_URL = 'data/my_roster.json';
  const LEAGUE_ROSTERS_URL = 'data/league_rosters.json';

  const DEDICATED = [
    { pos: 'QB', count: 1 },
    { pos: 'RB', count: 2 },
    { pos: 'WR', count: 2 },
    { pos: 'TE', count: 1 },
    { pos: 'K', count: 1 },
    { pos: 'DL', count: 2 },
    { pos: 'LB', count: 2 },
    { pos: 'DB', count: 2 },
  ];

  const FLEXES = [
    { eligible: ['RB', 'WR', 'TE'], count: 1 },
    { eligible: ['QB', 'RB', 'WR', 'TE'], count: 1 },
    { eligible: ['DL', 'LB', 'DB'], count: 2 },
  ];

  function normalizeFallback(name) {
    return String(name || '')
      .toLowerCase()
      .replace(/[.'’\-]/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function canonicalKey(name) {
    let key = typeof normalizeName === 'function'
      ? normalizeName(name)
      : normalizeFallback(name);

    if (typeof resolveExistingKey === 'function') {
      key = resolveExistingKey(key);
    }
    return key;
  }

  const fallbackPersonalSlots = Object.create(null);
  for (const name of ['devin neal', 'drew allar', 'michael trigg', 'bryce lance', 'derrick moore']) {
    fallbackPersonalSlots[canonicalKey(name)] = 'taxi';
  }

  const state = {
    marker: MARKER,
    projectionStatus: 'idle',
    projectionsBySleeperId: null,
    sleeperIdByKey: Object.create(null),
    personalSlotByKey: fallbackPersonalSlots,
    teamSlotByRosterId: Object.create(null),
  };

  global.TD_TEAM_UTILITY_RUNTIME = state;

  function capturePlayer(raw, slot, slotMap) {
    if (!raw) return;
    const key = canonicalKey(raw.name);
    if (!key) return;

    slotMap[key] = slot;

    if (raw.player_id !== undefined && raw.player_id !== null) {
      state.sleeperIdByKey[key] = String(raw.player_id);
    }
  }

  function capturePersonalRoster(data) {
    const slotMap = Object.create(null);

    for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {
      for (const raw of (data && data[slot]) || []) {
        capturePlayer(raw, slot, slotMap);
      }
    }

    for (const [key, slot] of Object.entries(fallbackPersonalSlots)) {
      if (!slotMap[key]) slotMap[key] = slot;
    }

    state.personalSlotByKey = slotMap;
  }

  function captureLeagueRosters(data) {
    const all = Object.create(null);

    for (const roster of (data && data.rosters) || []) {
      const slotMap = Object.create(null);

      for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {
        for (const raw of roster[slot] || []) {
          capturePlayer(raw, slot, slotMap);
        }
      }

      if (roster.roster_id !== undefined && roster.roster_id !== null) {
        all[String(roster.roster_id)] = slotMap;
      }
    }

    state.teamSlotByRosterId = all;
  }

  function currentSlotMap() {
    try {
      if (
        typeof MY_ROSTER_ID !== 'undefined' &&
        MY_ROSTER_ID !== null &&
        state.teamSlotByRosterId[String(MY_ROSTER_ID)]
      ) {
        return state.teamSlotByRosterId[String(MY_ROSTER_ID)];
      }
    } catch (_) {
      // Fall through to the personal roster map.
    }

    return state.personalSlotByKey;
  }

  function projectionByKey(key, pos) {
    if (pos === 'K') return null;
    if (state.projectionStatus !== 'ready' || !state.projectionsBySleeperId) {
      return null;
    }

    const sleeperId = state.sleeperIdByKey[key];
    if (!sleeperId) return null;

    const row = state.projectionsBySleeperId[String(sleeperId)];
    if (!row) return null;

    const projection = Number(row.projection);
    return Number.isFinite(projection) ? projection : null;
  }

  function lineupCompare(a, b) {
    if (a.pos === 'K' && b.pos === 'K') {
      return b.value - a.value;
    }

    const aHasProjection = Number.isFinite(a.lineupProjection);
    const bHasProjection = Number.isFinite(b.lineupProjection);

    if (aHasProjection && bHasProjection) {
      const diff = b.lineupProjection - a.lineupProjection;
      return diff !== 0 ? diff : (b.value - a.value);
    }

    if (aHasProjection !== bHasProjection) {
      return aHasProjection ? -1 : 1;
    }

    return b.value - a.value;
  }

  function buildPlayers(keys, slotByKey) {
    const out = [];

    for (const key of keys || []) {
      if (typeof PLAYER_DB === 'undefined') continue;
      const info = PLAYER_DB[key];
      if (!info) continue;

      const value = typeof playerValueByKey === 'function'
        ? playerValueByKey(key)
        : null;

      if (!Number.isFinite(value) || value <= 0) continue;

      const slot = (slotByKey && slotByKey[key]) || 'bench';

      out.push({
        key,
        pos: info.pos,
        value,
        lineupProjection: projectionByKey(key, info.pos),
        starterEligible: slot !== 'taxi' && slot !== 'reserve_ir',
        rosterSlot: slot,
      });
    }

    return out;
  }

  function optimizeLineup(players) {
    const remaining = (players || []).slice().sort(lineupCompare);
    const starters = [];

    for (const slot of DEDICATED) {
      for (let n = 0; n < slot.count; n += 1) {
        const index = remaining.findIndex(
          p => p.starterEligible !== false && p.pos === slot.pos
        );
        if (index < 0) break;
        starters.push(remaining[index]);
        remaining.splice(index, 1);
      }
    }

    for (const flex of FLEXES) {
      for (let n = 0; n < flex.count; n += 1) {
        const index = remaining.findIndex(
          p => p.starterEligible !== false && flex.eligible.includes(p.pos)
        );
        if (index < 0) break;
        starters.push(remaining[index]);
        remaining.splice(index, 1);
      }
    }

    return { starters, bench: remaining };
  }

  function sumValue(players) {
    return (players || []).reduce((sum, player) => sum + player.value, 0);
  }

  function buildPostSlotMap(preRosterKeys, postRosterKeys, preSlotByKey) {
    const preSet = new Set(preRosterKeys || []);
    const out = Object.create(null);

    for (const key of postRosterKeys || []) {
      out[key] = (
        preSet.has(key) &&
        preSlotByKey &&
        preSlotByKey[key]
      ) ? preSlotByKey[key] : 'bench';
    }

    return out;
  }

  function calculateTeamUtilityV1(
    preRosterKeys,
    postRosterKeys,
    preSlotByKey = currentSlotMap(),
    postSlotByKey = null
  ) {
    const resolvedPreSlots = preSlotByKey || Object.create(null);
    const resolvedPostSlots = postSlotByKey || buildPostSlotMap(
      preRosterKeys,
      postRosterKeys,
      resolvedPreSlots
    );

    const pre = optimizeLineup(buildPlayers(preRosterKeys, resolvedPreSlots));
    const post = optimizeLineup(buildPlayers(postRosterKeys, resolvedPostSlots));

    const lineupDelta = sumValue(post.starters) - sumValue(pre.starters);
    const benchDelta = sumValue(post.bench) - sumValue(pre.bench);

    const benchWeight = (
      typeof TU_BENCH_WEIGHT !== 'undefined' &&
      Number.isFinite(Number(TU_BENCH_WEIGHT))
    ) ? Number(TU_BENCH_WEIGHT) : 0.15;

    return {
      teamUtility: Math.round(
        (1 - benchWeight) * lineupDelta + benchWeight * benchDelta
      ),
      lineupDelta: Math.round(lineupDelta),
      benchDelta: Math.round(benchDelta),
    };
  }

  async function fetchJson(url) {
    const response = await fetch(url, { cache: 'no-store' });
    if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
    return response.json();
  }

  async function loadRuntimeData() {
    if (typeof fetch !== 'function') {
      state.projectionStatus = 'failed';
      return;
    }

    state.projectionStatus = 'loading';

    const [projectionResult, personalResult, leagueResult] = await Promise.allSettled([
      fetchJson(PROJECTION_URL),
      fetchJson(MY_ROSTER_URL),
      fetchJson(LEAGUE_ROSTERS_URL),
    ]);

    if (personalResult.status === 'fulfilled') {
      capturePersonalRoster(personalResult.value);
    } else {
      console.warn('Team Utility personal roster metadata unavailable:', personalResult.reason);
    }

    if (leagueResult.status === 'fulfilled') {
      captureLeagueRosters(leagueResult.value);
    } else {
      console.warn('Team Utility league roster metadata unavailable:', leagueResult.reason);
    }

    if (projectionResult.status === 'fulfilled') {
      const data = projectionResult.value;
      const players = data && data.players;
      const playerCount = players && typeof players === 'object'
        ? Object.keys(players).length
        : 0;

      if (
        data.schema_version === 1 &&
        Number(data.season) === 2026 &&
        playerCount >= 400
      ) {
        state.projectionsBySleeperId = players;
        state.projectionStatus = 'ready';
      } else {
        state.projectionsBySleeperId = null;
        state.projectionStatus = 'failed';
        console.warn('Unexpected Team Utility projection artifact schema/coverage');
      }
    } else {
      state.projectionsBySleeperId = null;
      state.projectionStatus = 'failed';
      console.warn(
        'Team Utility projection artifact unavailable; using Fundamental Value starter ordering:',
        projectionResult.reason
      );
    }

    if (typeof render === 'function') render();
  }

  function installBrowserRuntime() {
    global.calculateTeamUtility = calculateTeamUtilityV1;
    loadRuntimeData();
  }

  function selftest() {
    function p(key, pos, value, projection, slot = 'bench') {
      return {
        key,
        pos,
        value,
        lineupProjection: projection,
        starterEligible: slot !== 'taxi' && slot !== 'reserve_ir',
        rosterSlot: slot,
      };
    }

    const qb = optimizeLineup([
      p('high_fv_low_proj', 'QB', 9000, 100),
      p('low_fv_high_proj', 'QB', 3000, 300),
    ]);
    if (!qb.starters.some(player => player.key === 'low_fv_high_proj')) {
      throw new Error('projection objective failed');
    }

    const taxi = optimizeLineup([
      p('active_qb', 'QB', 1000, 100),
      p('taxi_qb', 'QB', 20000, 900, 'taxi'),
    ]);
    if (taxi.starters.some(player => player.key === 'taxi_qb')) {
      throw new Error('taxi starter guard failed');
    }
    if (!taxi.bench.some(player => player.key === 'taxi_qb')) {
      throw new Error('taxi disappeared from bench economics');
    }

    const ordered = [
      p('missing', 'WR', 10000, null),
      p('known_zero', 'WR', 1000, 0),
    ].sort(lineupCompare);
    if (ordered[0].key !== 'known_zero') {
      throw new Error('missing projection treated as zero');
    }

    const slots = buildPostSlotMap(
      ['taxi_keep', 'wr_keep'],
      ['taxi_keep', 'wr_keep', 'incoming'],
      { taxi_keep: 'taxi', wr_keep: 'bench' }
    );
    if (slots.taxi_keep !== 'taxi') {
      throw new Error('existing taxi state not preserved');
    }
    if (slots.incoming !== 'bench') {
      throw new Error('incoming asset not made starter-eligible');
    }

    const full = [];
    let id = 0;
    for (const [pos, count] of [
      ['QB', 2], ['RB', 3], ['WR', 3], ['TE', 2], ['K', 1],
      ['DL', 4], ['LB', 4], ['DB', 4],
    ]) {
      for (let i = 0; i < count; i += 1) {
        id += 1;
        full.push(p(`${pos}${id}`, pos, 1000 - id, 500 - id));
      }
    }

    const optimized = optimizeLineup(full);
    if (optimized.starters.length !== 17) {
      throw new Error(`expected 17 legal starters, got ${optimized.starters.length}`);
    }

    console.log('PASS Team Utility projection runtime self-test');
  }

  global.TD_TEAM_UTILITY_RUNTIME_API = {
    lineupCompare,
    optimizeLineup,
    buildPostSlotMap,
    calculateTeamUtilityV1,
    selftest,
  };

  if (
    typeof process !== 'undefined' &&
    process.argv &&
    process.argv.includes('--selftest')
  ) {
    selftest();
  } else if (typeof window !== 'undefined' && global === window) {
    installBrowserRuntime();
  }
})(typeof window !== 'undefined' ? window : globalThis);

/* Runtime-only player valuation integrity guard V1 — 2026-09-05
 *
 * A player first discovered through the live Sleeper roster merge must never
 * receive a Fundamental Value boost merely because a dynasty manager placed
 * him in a fantasy starter/bench slot. The inline legacy merge maps fantasy
 * starter/bench/taxi to Starter/Rotational/Speculative for previously unknown
 * players; this guard corrects that runtime-only path without changing any
 * baked PLAYER_DB, PROD_MULT, age curve, position weight, or frozen research
 * coefficient.
 *
 * Canonical/model-covered players remain on the existing valuation path.
 * Runtime-only players with no PROD_MULT fail conservatively at the canonical
 * 0.15 production floor until the normal model pipeline bakes real evidence.
 */
(function (global) {
  'use strict';

  const MARKER = 'RUNTIME_ONLY_PLAYER_VALUE_GUARD_V1';
  const MISSING_MODEL_FLOOR = 0.15;

  function fallbackKey(name) {
    return String(name || '')
      .toLowerCase()
      .replace(/[.'’\-]/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function keyFor(name) {
    let key = typeof normalizeName === 'function'
      ? normalizeName(name)
      : fallbackKey(name);
    if (typeof resolveExistingKey === 'function') key = resolveExistingKey(key);
    return key;
  }

  function hasCanonicalProduction(key) {
    return typeof PROD_MULT !== 'undefined' &&
      Object.prototype.hasOwnProperty.call(PROD_MULT, key);
  }

  function hasNoHistoryMarker(key) {
    return typeof NO_REAL_PRODUCTION_HISTORY !== 'undefined' &&
      Object.prototype.hasOwnProperty.call(NO_REAL_PRODUCTION_HISTORY, key);
  }

  function runtimeRoleFromDepth(pos, depthChartOrder) {
    const depth = Number(depthChartOrder);
    if (pos === 'QB') {
      if (depth === 1) return 'Starter';
      if (depth === 2) return 'Understudy';
      if (Number.isFinite(depth) && depth >= 3) return 'Speculative';
    }
    return 'Speculative';
  }

  function guardedProductionValue(isRuntimeOnly, hasProduction, originalValue) {
    return isRuntimeOnly && !hasProduction ? MISSING_MODEL_FLOOR : originalValue;
  }

  function applyRuntimeMetadata(raw, beforeKeys) {
    if (!raw || typeof PLAYER_DB === 'undefined') return;
    const key = keyFor(raw.name);
    if (!key) return;
    const info = PLAYER_DB[key];
    if (!info) return;

    const wasNew = beforeKeys && !beforeKeys.has(key);
    if (!wasNew && !info.runtimeSyncedOnly) return;

    info.runtimeSyncedOnly = true;
    info.depth_chart_order = raw.depth_chart_order ?? info.depth_chart_order ?? null;
    info.years_exp = raw.years_exp ?? info.years_exp ?? null;
    info.role = runtimeRoleFromDepth(info.pos, info.depth_chart_order);
  }

  function applyPersonalPayload(data, beforeKeys) {
    for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {
      for (const raw of (data && data[slot]) || []) {
        applyRuntimeMetadata(raw, beforeKeys);
      }
    }
  }

  function applyLeaguePayload(data, beforeKeys) {
    for (const roster of (data && data.rosters) || []) {
      for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {
        for (const raw of roster[slot] || []) {
          applyRuntimeMetadata(raw, beforeKeys);
        }
      }
    }
  }

  function recoverAlreadyMergedRuntimeQBs() {
    if (typeof PLAYER_DB === 'undefined') return;
    for (const [key, info] of Object.entries(PLAYER_DB)) {
      if (!info || info.pos !== 'QB' || info.currentlyRostered !== true) continue;
      if (hasCanonicalProduction(key) || hasNoHistoryMarker(key)) continue;
      if (info.pts2025 !== undefined || info.proj2026 !== undefined) continue;
      info.runtimeSyncedOnly = true;
      info.role = runtimeRoleFromDepth(info.pos, info.depth_chart_order);
    }
  }

  function installBrowserGuard() {
    if (
      typeof PLAYER_DB === 'undefined' ||
      typeof global.productionMultiplier !== 'function'
    ) {
      console.warn(`${MARKER}: valuation globals unavailable; guard not installed`);
      return;
    }

    const originalProductionMultiplier = global.productionMultiplier;
    global.productionMultiplier = function runtimeGuardedProductionMultiplier(name, role) {
      const key = keyFor(name);
      const info = PLAYER_DB[key];
      const originalValue = originalProductionMultiplier(name, role);
      return guardedProductionValue(
        !!(info && info.runtimeSyncedOnly),
        hasCanonicalProduction(key),
        originalValue
      );
    };

    if (typeof global.mergeLiveRoster === 'function') {
      const originalMergeLiveRoster = global.mergeLiveRoster;
      global.mergeLiveRoster = function runtimeGuardedMergeLiveRoster(data) {
        const beforeKeys = new Set(Object.keys(PLAYER_DB));
        const result = originalMergeLiveRoster(data);
        applyPersonalPayload(data, beforeKeys);
        return result;
      };
    }

    if (typeof global.mergeLeagueRosters === 'function') {
      const originalMergeLeagueRosters = global.mergeLeagueRosters;
      global.mergeLeagueRosters = function runtimeGuardedMergeLeagueRosters(data) {
        const beforeKeys = new Set(Object.keys(PLAYER_DB));
        const result = originalMergeLeagueRosters(data);
        applyLeaguePayload(data, beforeKeys);
        return result;
      };
    }

    recoverAlreadyMergedRuntimeQBs();
    global.TD_RUNTIME_PLAYER_VALUE_GUARD = {
      marker: MARKER,
      floor: MISSING_MODEL_FLOOR,
      runtimeRoleFromDepth,
    };
  }

  function selftest() {
    const roles = [
      runtimeRoleFromDepth('QB', 1),
      runtimeRoleFromDepth('QB', 2),
      runtimeRoleFromDepth('QB', 3),
      runtimeRoleFromDepth('QB', null),
      runtimeRoleFromDepth('WR', 1),
    ];
    const expectedRoles = ['Starter', 'Understudy', 'Speculative', 'Speculative', 'Speculative'];
    if (JSON.stringify(roles) !== JSON.stringify(expectedRoles)) {
      throw new Error(`runtime depth-role guard failed: ${JSON.stringify(roles)}`);
    }

    const slotInflationInputs = [1.0, 0.65, 0.57, 0.22];
    for (const originalValue of slotInflationInputs) {
      if (guardedProductionValue(true, false, originalValue) !== MISSING_MODEL_FLOOR) {
        throw new Error('runtime missing-model floor depends on fantasy/role estimate');
      }
    }
    if (guardedProductionValue(false, false, 0.65) !== 0.65) {
      throw new Error('curated missing-production fallback changed');
    }
    if (guardedProductionValue(true, true, 0.65) !== 0.65) {
      throw new Error('canonical production was overridden');
    }

    console.log('PASS Runtime-only player valuation guard self-test');
  }

  if (
    typeof process !== 'undefined' &&
    process.argv &&
    process.argv.includes('--selftest')
  ) {
    selftest();
  } else if (typeof window !== 'undefined' && global === window) {
    installBrowserGuard();
  }
})(typeof window !== 'undefined' ? window : globalThis);
/* LOG_APP_HEADER_NAV_V1
 * Presentation-only shell for the Trade Desk.
 * - Does not modify valuation/model constants.
 * - Does not alter PLAYER_DB, PROD_MULT_DATA, ROLE_MULT, AGE_CURVE,
 *   POSITION_WEIGHT, trade math, or Team Utility accounting.
 * - index.html remains untouched; remove this IIFE to restore the prior UI.
 */
(function installLogAppHeaderNavV1() {
  'use strict';

  const MARKER = 'LOG_APP_HEADER_NAV_V1';

  // Node/self-test execution has no DOM. Keep the presentation layer inert.
  if (typeof document === 'undefined') return;

  function init() {
    const root = document.documentElement;
    if (!root || root.dataset.logAppHeaderNavV1 === '1') return;

    const wrap = document.querySelector('.wrap');
    const pageHeader = wrap && wrap.querySelector('header');
    if (!wrap || !pageHeader || !document.head || !document.body) return;

    root.dataset.logAppHeaderNavV1 = '1';

    const style = document.createElement('style');
    style.id = 'log-app-header-nav-v1-styles';
    style.textContent = `
      :root{
        --log-app-deep:#091B2C;
        --log-app-bar:rgba(9,27,44,.965);
        --log-app-hover:rgba(255,255,255,.055);
      }

      html{scroll-behavior:smooth}

      .log-app-shell{
        position:sticky;
        top:0;
        z-index:1000;
        width:100%;
        background:var(--log-app-bar);
        border-bottom:1px solid var(--line);
        box-shadow:0 8px 30px rgba(0,0,0,.18);
        -webkit-backdrop-filter:blur(18px);
        backdrop-filter:blur(18px);
      }
      .log-app-topbar,
      .log-app-nav-inner{
        width:min(1180px, calc(100% - 32px));
        margin:0 auto;
      }
      .log-app-topbar{
        min-height:66px;
        display:flex;
        align-items:center;
        gap:13px;
        padding:9px 0 8px;
      }
      .log-app-logo{
        width:44px;
        height:44px;
        object-fit:contain;
        flex:0 0 auto;
        filter:drop-shadow(0 4px 12px rgba(235,98,97,.20));
      }
      .log-app-brand{
        min-width:0;
        display:flex;
        flex-direction:column;
        gap:2px;
      }
      .log-app-brand-title{
        font-family:'Anton',sans-serif;
        font-size:17px;
        line-height:1.05;
        text-transform:uppercase;
        letter-spacing:.035em;
        color:var(--text);
        white-space:nowrap;
      }
      .log-app-brand-sub{
        font-family:'IBM Plex Mono',monospace;
        font-size:9.5px;
        line-height:1.25;
        letter-spacing:.075em;
        text-transform:uppercase;
        color:var(--text-muted);
        white-space:nowrap;
        overflow:hidden;
        text-overflow:ellipsis;
        max-width:420px;
      }
      .log-app-context{
        margin-left:auto;
        display:flex;
        align-items:center;
        justify-content:flex-end;
        gap:14px;
        min-width:0;
      }
      .log-app-league{
        text-align:right;
        min-width:0;
      }
      .log-app-league-label{
        font-family:'IBM Plex Mono',monospace;
        font-size:8px;
        letter-spacing:.12em;
        text-transform:uppercase;
        color:var(--text-dim);
        margin-bottom:2px;
      }
      .log-app-league-name{
        font-size:11px;
        font-weight:700;
        color:var(--text-muted);
        white-space:nowrap;
      }
      .log-app-status{
        display:flex;
        align-items:center;
        gap:7px;
        min-height:27px;
        padding:0 9px;
        border:1px solid var(--line-strong);
        border-radius:999px;
        background:rgba(255,255,255,.025);
        font-family:'IBM Plex Mono',monospace;
        font-size:8.5px;
        font-weight:600;
        letter-spacing:.08em;
        color:var(--text-muted);
        white-space:nowrap;
      }
      .log-app-status-dot{
        width:7px;
        height:7px;
        border-radius:50%;
        flex:0 0 auto;
        background:var(--amber);
        box-shadow:0 0 8px rgba(232,184,75,.42);
      }
      .log-app-status.is-live{
        color:var(--green);
        border-color:rgba(63,203,124,.25);
        background:rgba(63,203,124,.06);
      }
      .log-app-status.is-live .log-app-status-dot{
        background:var(--green);
        box-shadow:0 0 8px rgba(63,203,124,.62);
      }
      .log-app-status.is-fail{
        color:var(--red);
        border-color:rgba(255,138,76,.30);
        background:rgba(255,138,76,.06);
      }
      .log-app-status.is-fail .log-app-status-dot{
        background:var(--red);
        box-shadow:0 0 8px rgba(255,138,76,.55);
      }
      .log-app-sync{
        font-family:'IBM Plex Mono',monospace;
        font-size:8.5px;
        line-height:1.2;
        color:var(--text-dim);
        white-space:nowrap;
      }

      .log-app-nav{
        border-top:1px solid rgba(201,206,210,.07);
        background:rgba(4,14,24,.12);
      }
      .log-app-nav-inner{
        min-height:42px;
        display:flex;
        align-items:stretch;
        gap:3px;
      }
      .log-app-nav-item{
        position:relative;
        display:flex;
        align-items:center;
        justify-content:center;
        gap:7px;
        min-width:0;
        padding:0 14px;
        border:0;
        border-radius:0;
        background:transparent;
        color:var(--text-muted);
        text-decoration:none;
        font-family:'Inter',sans-serif;
        font-size:11.5px;
        font-weight:700;
        cursor:pointer;
        white-space:nowrap;
        transition:background .15s ease,color .15s ease;
      }
      .log-app-nav-item:hover{
        background:var(--log-app-hover);
        color:var(--text);
      }
      .log-app-nav-item.is-active{
        color:var(--text);
        background:rgba(235,98,97,.065);
      }
      .log-app-nav-item.is-active::after{
        content:'';
        position:absolute;
        left:11px;
        right:11px;
        bottom:0;
        height:2px;
        border-radius:2px 2px 0 0;
        background:var(--gold);
        box-shadow:0 0 10px rgba(235,98,97,.32);
      }
      .log-app-nav-icon{
        font-family:'IBM Plex Mono',monospace;
        font-size:9px;
        color:var(--text-dim);
      }
      .log-app-nav-item.is-active .log-app-nav-icon{
        color:var(--gold);
      }

      /* The old logo is moved into the app shell. The original page header
         remains the page-level "Trade Desk" title/context block. */
      .log-page-header{
        padding-top:18px !important;
        padding-bottom:18px !important;
        margin-bottom:18px !important;
      }
      .log-page-header > .league-logo{
        display:none !important;
      }
      .log-page-header > .eyebrow{
        margin-bottom:6px !important;
        color:var(--text-dim) !important;
        font-size:9.5px !important;
      }
      .log-page-header > h1{
        font-size:31px !important;
        margin-bottom:7px !important;
        text-shadow:none !important;
      }
      .log-page-header > p{
        max-width:62ch !important;
        line-height:1.5 !important;
      }

      @media (max-width:760px){
        .log-app-topbar,
        .log-app-nav-inner{
          width:min(100% - 22px, 1180px);
        }
        .log-app-topbar{
          min-height:58px;
          gap:10px;
          padding:7px 0;
        }
        .log-app-logo{
          width:38px;
          height:38px;
        }
        .log-app-brand-title{
          font-size:14px;
        }
        .log-app-brand-sub{
          max-width:48vw;
          font-size:8px;
        }
        .log-app-league,
        .log-app-sync{
          display:none;
        }
        .log-app-context{
          gap:8px;
        }
        .log-app-status{
          padding:0 8px;
          min-height:25px;
          font-size:7.5px;
        }
        .log-app-nav-inner{
          min-height:40px;
          overflow-x:auto;
          scrollbar-width:none;
        }
        .log-app-nav-inner::-webkit-scrollbar{display:none}
        .log-app-nav-item{
          flex:1 0 auto;
          padding:0 11px;
          font-size:10.5px;
        }
        .log-page-header{
          padding-top:14px !important;
        }
        .log-page-header > h1{
          font-size:28px !important;
        }
      }

      @media (max-width:430px){
        .log-app-brand-sub{
          max-width:42vw;
        }
        .log-app-status{
          padding:0 7px;
        }
        .log-app-status-text{
          max-width:58px;
          overflow:hidden;
          text-overflow:ellipsis;
        }
      }
    `;
    document.head.appendChild(style);

    const existingLogo = pageHeader.querySelector('.league-logo');

    const shell = document.createElement('div');
    shell.className = 'log-app-shell';
    shell.setAttribute('data-ui-marker', MARKER);
    shell.innerHTML = `
      <div class="log-app-topbar">
        <div class="log-app-logo-slot" aria-hidden="true"></div>
        <div class="log-app-brand">
          <div class="log-app-brand-title">Claude Dynasty Trade Calculator</div>
          <div class="log-app-brand-sub">League of Ordinary Gentlemen · IDP Dynasty</div>
        </div>
        <div class="log-app-context">
          <div class="log-app-league">
            <div class="log-app-league-label">Current League</div>
            <div class="log-app-league-name">League of Ordinary Gentlemen</div>
          </div>
          <div class="log-app-status" id="logAppModelStatus" role="status" aria-live="polite">
            <span class="log-app-status-dot"></span>
            <span class="log-app-status-text">SYNCING</span>
          </div>
          <div class="log-app-sync" id="logAppLastSync">Last sync: —</div>
        </div>
      </div>
      <div class="log-app-nav">
        <nav class="log-app-nav-inner" aria-label="Primary">
          <button class="log-app-nav-item is-active" id="logNavTradeDesk" type="button" aria-current="page">
            <span class="log-app-nav-icon">◆</span>
            <span>Trade Desk</span>
          </button>
          <button class="log-app-nav-item" id="logNavMyTeam" type="button">
            <span class="log-app-nav-icon">▦</span>
            <span>My Team</span>
          </button>
          <a class="log-app-nav-item" id="logNavFreeAgents" href="free-agent-board.html">
            <span class="log-app-nav-icon">＋</span>
            <span>Free Agents</span>
          </a>
        </nav>
      </div>
    `;

    if (existingLogo) {
      const clone = existingLogo.cloneNode(true);
      clone.className = 'log-app-logo';
      clone.removeAttribute('style');
      const slot = shell.querySelector('.log-app-logo-slot');
      if (slot) slot.replaceWith(clone);
    }

    document.body.insertBefore(shell, wrap);
    pageHeader.classList.add('log-page-header');

    const navTrade = shell.querySelector('#logNavTradeDesk');
    const navTeam = shell.querySelector('#logNavMyTeam');
    const navFreeAgents = shell.querySelector('#logNavFreeAgents');

    function setActive(active) {
      for (const item of [navTrade, navTeam, navFreeAgents]) {
        if (!item) continue;
        item.classList.toggle('is-active', item === active);
        if (item === active) item.setAttribute('aria-current', 'page');
        else item.removeAttribute('aria-current');
      }
    }

    if (navTrade) {
      navTrade.addEventListener('click', function () {
        setActive(navTrade);
        window.scrollTo({ top: 0, behavior: 'smooth' });
      });
    }

    if (navTeam) {
      navTeam.addEventListener('click', function () {
        setActive(navTeam);

        const fullRoster = document.getElementById('fullRosterDetails');
        if (fullRoster) fullRoster.open = true;

        const target =
          document.getElementById('needsWrap') ||
          fullRoster ||
          pageHeader;

        if (target && typeof target.scrollIntoView === 'function') {
          target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      });
    }

    // Mirror the real roster/league sync state in the global badge.
    const globalStatus = shell.querySelector('#logAppModelStatus');
    const globalStatusText = shell.querySelector('.log-app-status-text');
    const sourceStatuses = [
      document.getElementById('liveStatus'),
      document.getElementById('leagueSyncStatus')
    ].filter(Boolean);

    function updateGlobalStatus() {
      if (!globalStatus || !globalStatusText) return;

      const dots = sourceStatuses
        .map(el => el.querySelector('.live-dot'))
        .filter(Boolean);

      const anyFail = dots.some(dot => dot.classList.contains('fail'));
      const allLive = dots.length > 0 && dots.every(dot => dot.classList.contains('ok'));

      globalStatus.classList.toggle('is-live', allLive && !anyFail);
      globalStatus.classList.toggle('is-fail', anyFail);

      globalStatusText.textContent = anyFail
        ? 'SYNC ISSUE'
        : (allLive ? 'LIVE MODEL' : 'SYNCING');
    }

    updateGlobalStatus();

    if (typeof MutationObserver !== 'undefined') {
      const observer = new MutationObserver(updateGlobalStatus);
      for (const el of sourceStatuses) {
        observer.observe(el, {
          attributes: true,
          childList: true,
          subtree: true,
          characterData: true
        });
      }
    }

    // Last-sync time is display-only and comes from the already-committed
    // Sleeper timestamp artifact. A fetch failure simply leaves the dash.
    const syncLabel = shell.querySelector('#logAppLastSync');
    if (syncLabel && typeof fetch === 'function') {
      fetch('data/last_synced.json', { cache: 'no-store' })
        .then(resp => resp.ok ? resp.json() : null)
        .then(doc => {
          if (!doc) return;
          const raw = doc.synced_at_readable;
          if (raw) {
            syncLabel.textContent = 'Last sync: ' + String(raw).replace(' UTC', 'Z');
            return;
          }
          const epoch = Number(doc.synced_at);
          if (Number.isFinite(epoch)) {
            syncLabel.textContent = 'Last sync: ' + new Date(epoch * 1000).toLocaleString();
          }
        })
        .catch(() => {});
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init, { once: true });
  } else {
    init();
  }
})();
