/* Team Utility Projection Runtime V1
 *
 * Projection points choose WHO starts.
 * Fundamental Value remains the ONLY accounting unit for lineupDelta,
 * benchDelta, and final Team Utility.
 *
 * This file is generated by the Python deployment patcher. It intentionally
 * lives outside index.html so the giant static PLAYER_DB is never rewritten.
 */
(function (global) {
  'use strict';

  const MARKER = 'TEAM_UTILITY_PROJECTION_RUNTIME_V1';
  const PROJECTION_URL = 'scripts/artifacts/generated/team_utility_lineup_projections.json';
  const MY_ROSTER_URL = 'data/my_roster.json';
  const LEAGUE_ROSTERS_URL = 'data/league_rosters.json';

  const DEDICATED = [
    { pos: 'QB', count: 1 },
    { pos: 'RB', count: 2 },
    { pos: 'WR', count: 2 },
    { pos: 'TE', count: 1 },
    { pos: 'K', count: 1 },
    { pos: 'DL', count: 2 },
    { pos: 'LB', count: 2 },
    { pos: 'DB', count: 2 },
  ];

  const FLEXES = [
    { eligible: ['RB', 'WR', 'TE'], count: 1 },
    { eligible: ['QB', 'RB', 'WR', 'TE'], count: 1 },
    { eligible: ['DL', 'LB', 'DB'], count: 2 },
  ];

  function normalizeFallback(name) {
    return String(name || '')
      .toLowerCase()
      .replace(/[.'’\-]/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function canonicalKey(name) {
    let key = typeof normalizeName === 'function'
      ? normalizeName(name)
      : normalizeFallback(name);

    if (typeof resolveExistingKey === 'function') {
      key = resolveExistingKey(key);
    }
    return key;
  }

  const fallbackPersonalSlots = Object.create(null);
  for (const name of ['devin neal', 'drew allar', 'michael trigg', 'bryce lance', 'derrick moore']) {
    fallbackPersonalSlots[canonicalKey(name)] = 'taxi';
  }

  const state = {
    marker: MARKER,
    projectionStatus: 'idle',
    projectionsBySleeperId: null,
    sleeperIdByKey: Object.create(null),
    personalSlotByKey: fallbackPersonalSlots,
    teamSlotByRosterId: Object.create(null),
  };

  global.TD_TEAM_UTILITY_RUNTIME = state;

  function capturePlayer(raw, slot, slotMap) {
    if (!raw) return;
    const key = canonicalKey(raw.name);
    if (!key) return;

    slotMap[key] = slot;

    if (raw.player_id !== undefined && raw.player_id !== null) {
      state.sleeperIdByKey[key] = String(raw.player_id);
    }
  }

  function capturePersonalRoster(data) {
    const slotMap = Object.create(null);

    for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {
      for (const raw of (data && data[slot]) || []) {
        capturePlayer(raw, slot, slotMap);
      }
    }

    // Keep known fallback taxi metadata if a future source snapshot omits it.
    for (const [key, slot] of Object.entries(fallbackPersonalSlots)) {
      if (!slotMap[key]) slotMap[key] = slot;
    }

    state.personalSlotByKey = slotMap;
  }

  function captureLeagueRosters(data) {
    const all = Object.create(null);

    for (const roster of (data && data.rosters) || []) {
      const slotMap = Object.create(null);

      for (const slot of ['starters', 'bench', 'taxi', 'reserve_ir']) {
        for (const raw of roster[slot] || []) {
          capturePlayer(raw, slot, slotMap);
        }
      }

      if (roster.roster_id !== undefined && roster.roster_id !== null) {
        all[String(roster.roster_id)] = slotMap;
      }
    }

    state.teamSlotByRosterId = all;
  }

  function currentSlotMap() {
    try {
      if (
        typeof MY_ROSTER_ID !== 'undefined' &&
        MY_ROSTER_ID !== null &&
        state.teamSlotByRosterId[String(MY_ROSTER_ID)]
      ) {
        return state.teamSlotByRosterId[String(MY_ROSTER_ID)];
      }
    } catch (_) {
      // Fall through to the personal roster map.
    }

    return state.personalSlotByKey;
  }

  function projectionByKey(key, pos) {
    if (pos === 'K') return null;
    if (state.projectionStatus !== 'ready' || !state.projectionsBySleeperId) {
      return null;
    }

    const sleeperId = state.sleeperIdByKey[key];
    if (!sleeperId) return null;

    const row = state.projectionsBySleeperId[String(sleeperId)];
    if (!row) return null;

    const projection = Number(row.projection);
    return Number.isFinite(projection) ? projection : null;
  }

  function lineupCompare(a, b) {
    // The canonical projection artifact intentionally omits kickers.
    if (a.pos === 'K' && b.pos === 'K') {
      return b.value - a.value;
    }

    const aHasProjection = Number.isFinite(a.lineupProjection);
    const bHasProjection = Number.isFinite(b.lineupProjection);

    if (aHasProjection && bHasProjection) {
      const diff = b.lineupProjection - a.lineupProjection;
      return diff !== 0 ? diff : (b.value - a.value);
    }

    // Missing projection is unknown, never interpreted as zero.
    if (aHasProjection !== bHasProjection) {
      return aHasProjection ? -1 : 1;
    }

    // Safe fallback reproduces the prior FV starter ordering.
    return b.value - a.value;
  }

  function buildPlayers(keys, slotByKey) {
    const out = [];

    for (const key of keys || []) {
      if (typeof PLAYER_DB === 'undefined') continue;
      const info = PLAYER_DB[key];
      if (!info) continue;

      const value = typeof playerValueByKey === 'function'
        ? playerValueByKey(key)
        : null;

      if (!Number.isFinite(value) || value <= 0) continue;

      const slot = (slotByKey && slotByKey[key]) || 'bench';

      out.push({
        key,
        pos: info.pos,
        value,
        lineupProjection: projectionByKey(key, info.pos),
        starterEligible: slot !== 'taxi' && slot !== 'reserve_ir',
        rosterSlot: slot,
      });
    }

    return out;
  }

  function optimizeLineup(players) {
    const remaining = (players || []).slice().sort(lineupCompare);
    const starters = [];

    for (const slot of DEDICATED) {
      for (let n = 0; n < slot.count; n += 1) {
        const index = remaining.findIndex(
          p => p.starterEligible !== false && p.pos === slot.pos
        );
        if (index < 0) break;
        starters.push(remaining[index]);
        remaining.splice(index, 1);
      }
    }

    for (const flex of FLEXES) {
      for (let n = 0; n < flex.count; n += 1) {
        const index = remaining.findIndex(
          p => p.starterEligible !== false && flex.eligible.includes(p.pos)
        );
        if (index < 0) break;
        starters.push(remaining[index]);
        remaining.splice(index, 1);
      }
    }

    return { starters, bench: remaining };
  }

  function sumValue(players) {
    return (players || []).reduce((sum, player) => sum + player.value, 0);
  }

  function buildPostSlotMap(preRosterKeys, postRosterKeys, preSlotByKey) {
    const preSet = new Set(preRosterKeys || []);
    const out = Object.create(null);

    for (const key of postRosterKeys || []) {
      // Existing assets retain their current roster state.
      // Incoming trade assets default to active bench and are startable.
      out[key] = (
        preSet.has(key) &&
        preSlotByKey &&
        preSlotByKey[key]
      ) ? preSlotByKey[key] : 'bench';
    }

    return out;
  }

  function calculateTeamUtilityV1(
    preRosterKeys,
    postRosterKeys,
    preSlotByKey = currentSlotMap(),
    postSlotByKey = null
  ) {
    const resolvedPreSlots = preSlotByKey || Object.create(null);
    const resolvedPostSlots = postSlotByKey || buildPostSlotMap(
      preRosterKeys,
      postRosterKeys,
      resolvedPreSlots
    );

    const pre = optimizeLineup(buildPlayers(preRosterKeys, resolvedPreSlots));
    const post = optimizeLineup(buildPlayers(postRosterKeys, resolvedPostSlots));

    const lineupDelta = sumValue(post.starters) - sumValue(pre.starters);
    const benchDelta = sumValue(post.bench) - sumValue(pre.bench);

    // The existing production constant remains authoritative. 0.15 is only
    // the defensive fallback if the constant is unavailable.
    const benchWeight = (
      typeof TU_BENCH_WEIGHT !== 'undefined' &&
      Number.isFinite(Number(TU_BENCH_WEIGHT))
    ) ? Number(TU_BENCH_WEIGHT) : 0.15;

    return {
      teamUtility: Math.round(
        (1 - benchWeight) * lineupDelta + benchWeight * benchDelta
      ),
      lineupDelta: Math.round(lineupDelta),
      benchDelta: Math.round(benchDelta),
    };
  }

  async function fetchJson(url) {
    const response = await fetch(url, { cache: 'no-store' });
    if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
    return response.json();
  }

  async function loadRuntimeData() {
    if (typeof fetch !== 'function') {
      state.projectionStatus = 'failed';
      return;
    }

    state.projectionStatus = 'loading';

    const [projectionResult, personalResult, leagueResult] = await Promise.allSettled([
      fetchJson(PROJECTION_URL),
      fetchJson(MY_ROSTER_URL),
      fetchJson(LEAGUE_ROSTERS_URL),
    ]);

    if (personalResult.status === 'fulfilled') {
      capturePersonalRoster(personalResult.value);
    } else {
      console.warn('Team Utility personal roster metadata unavailable:', personalResult.reason);
    }

    if (leagueResult.status === 'fulfilled') {
      captureLeagueRosters(leagueResult.value);
    } else {
      console.warn('Team Utility league roster metadata unavailable:', leagueResult.reason);
    }

    if (projectionResult.status === 'fulfilled') {
      const data = projectionResult.value;
      const players = data && data.players;
      const playerCount = players && typeof players === 'object'
        ? Object.keys(players).length
        : 0;

      if (
        data.schema_version === 1 &&
        Number(data.season) === 2026 &&
        playerCount >= 400
      ) {
        state.projectionsBySleeperId = players;
        state.projectionStatus = 'ready';
      } else {
        state.projectionsBySleeperId = null;
        state.projectionStatus = 'failed';
        console.warn('Unexpected Team Utility projection artifact schema/coverage');
      }
    } else {
      state.projectionsBySleeperId = null;
      state.projectionStatus = 'failed';
      console.warn(
        'Team Utility projection artifact unavailable; using Fundamental Value starter ordering:',
        projectionResult.reason
      );
    }

    if (typeof render === 'function') render();
  }

  function installBrowserRuntime() {
    // Existing UI calls the global function by name. Override only that public
    // entry point; all static player/value code stays untouched.
    global.calculateTeamUtility = calculateTeamUtilityV1;
    loadRuntimeData();
  }

  function selftest() {
    function p(key, pos, value, projection, slot = 'bench') {
      return {
        key,
        pos,
        value,
        lineupProjection: projection,
        starterEligible: slot !== 'taxi' && slot !== 'reserve_ir',
        rosterSlot: slot,
      };
    }

    const qb = optimizeLineup([
      p('high_fv_low_proj', 'QB', 9000, 100),
      p('low_fv_high_proj', 'QB', 3000, 300),
    ]);
    if (!qb.starters.some(player => player.key === 'low_fv_high_proj')) {
      throw new Error('projection objective failed');
    }

    const taxi = optimizeLineup([
      p('active_qb', 'QB', 1000, 100),
      p('taxi_qb', 'QB', 20000, 900, 'taxi'),
    ]);
    if (taxi.starters.some(player => player.key === 'taxi_qb')) {
      throw new Error('taxi starter guard failed');
    }
    if (!taxi.bench.some(player => player.key === 'taxi_qb')) {
      throw new Error('taxi disappeared from bench economics');
    }

    const ordered = [
      p('missing', 'WR', 10000, null),
      p('known_zero', 'WR', 1000, 0),
    ].sort(lineupCompare);
    if (ordered[0].key !== 'known_zero') {
      throw new Error('missing projection treated as zero');
    }

    const slots = buildPostSlotMap(
      ['taxi_keep', 'wr_keep'],
      ['taxi_keep', 'wr_keep', 'incoming'],
      { taxi_keep: 'taxi', wr_keep: 'bench' }
    );
    if (slots.taxi_keep !== 'taxi') {
      throw new Error('existing taxi state not preserved');
    }
    if (slots.incoming !== 'bench') {
      throw new Error('incoming asset not made starter-eligible');
    }

    const full = [];
    let id = 0;
    for (const [pos, count] of [
      ['QB', 2], ['RB', 3], ['WR', 3], ['TE', 2], ['K', 1],
      ['DL', 4], ['LB', 4], ['DB', 4],
    ]) {
      for (let i = 0; i < count; i += 1) {
        id += 1;
        full.push(p(`${pos}${id}`, pos, 1000 - id, 500 - id));
      }
    }

    const optimized = optimizeLineup(full);
    if (optimized.starters.length !== 17) {
      throw new Error(`expected 17 legal starters, got ${optimized.starters.length}`);
    }

    console.log('PASS Team Utility projection runtime self-test');
  }

  global.TD_TEAM_UTILITY_RUNTIME_API = {
    lineupCompare,
    optimizeLineup,
    buildPostSlotMap,
    calculateTeamUtilityV1,
    selftest,
  };

  if (
    typeof process !== 'undefined' &&
    process.argv &&
    process.argv.includes('--selftest')
  ) {
    selftest();
  } else if (typeof window !== 'undefined' && global === window) {
    installBrowserRuntime();
  }
})(typeof window !== 'undefined' ? window : globalThis);
